spring:
  application:
    name: realtime-chat

  datasource:
    url: jdbc:postgresql://localhost:5434/chat
    username: chat
    password: chat1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  data:
    redis:
      host: localhost
      port: 6380

server:
  port: 8085

jwt:
  secret: realtime-chat-secret-key-must-be-at-least-32-bytes-long
  expiration-ms: 3600000

cloud:
  aws:
    s3:
      endpoint: http://localhost:9000
      region: us-east-1
      bucket: chat-files
      access-key: minioadmin
      secret-key: minioadmin
